MGMT-8156: Extract strings for localization
openshift-assisted/assisted-ui pull request #573
Opened 2022-06-29 08:01 UTC by ammont82

To resolve problems with localization implemented in assisted-ui-lib we need to add the i18n configuration to assisted-ui project.

Related to https://github.com/stolostron/console/pull/1710

Related to https://issues.redhat.com/browse/MGMT-8156

More info: https://docs.google.com/document/d/1KxjA8qsKA3K81MQrMF4jt0Ope4EM0lHWAN0emUx-q4w/edit

Depends on https://github.com/openshift-assisted/assisted-ui-lib/pull/1484.

2022-06-29 11:36 UTC, jtomasek requested changes

2022-06-29 11:36 UTC, jtomasek commented on src/i18n.js
> +    contextSeparator: '~',
We should not override this. Keep it default ('_')

2022-06-29 11:36 UTC, jtomasek commented on src/i18n.js
> +import translation from './locales/en/translation.json';
Don't copy the file to assisted-ui. The translations should always be imported from assisted-ui-lib. They are available from
```
import locales from 'openshift-assisted-ui-lib/locales'
```

2022-06-29 11:36 UTC, jtomasek commented on src/i18n.js
> +    assisted_installer: translation,
this namespace is incorrect IIUC

2022-06-29 11:36 UTC, jtomasek commented on src/i18n.js
> +};
```suggestion
const resources = locales;
```

2022-06-30 06:56 UTC, celdrake commented
Please, update also the README to reflect the new environment variable and indicate which value should be used.

2022-07-06 07:17 UTC, celdrake approved these changes

2022-07-11 07:24 UTC, jkilzi approved these changes

2022-07-11 07:42 UTC, merged